#!/bin/bash

if ! tmux has-session -t x
then
  echo "No session"
  exit 0
fi

# Function to kill a tmux window by name, by sending Ctrl+C
# to the window.
kill_window() {
  local window_name="$1"
  local window_id=$(tmux list-windows -t x -F '#{window_index} #{window_name}' | grep "$window_name" | cut -d' ' -f1)
  if [ -n "$window_id" ]
  then
    tmux send-keys -t x:$window_id C-c
    sleep 0.5
    tmux send-keys -t x:$window_id C-c
  fi
}

kill_window vnc "$DIR/service-xtigervnc"
kill_window session "$DIR/service-session"
